# Generated by Django 5.0.6 on 2026-06-30 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverdueLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_past_due', models.IntegerField()),
                ('total_overdue_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('written_off', 'Written Off')], default='pending', max_length=20)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_contact_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_record', to='loans.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('visit', 'Visit'), ('legal', 'Legal Action')], max_length=20)),
                ('description', models.TextField()),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('overdue_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='recovery.overdueloan')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
