# Generated by Django 5.0.6 on 2026-06-29 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('financial', 'Financial Report'), ('portfolio', 'Portfolio Analysis'), ('cashflow', 'Cash Flow Report'), ('overdue', 'Overdue Report'), ('custom', 'Custom Report')], max_length=20)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
